development:
  adapter: postgresql
  encoding: utf8
  database: coursadomicile
  username: JFP
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: coursadomicile
  username: JFP
  password: 