default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: coursadomicile_development

test:
  <<: *default
  database: coursadomicile_test

staging:
  <<: *default
  database: coursadomicile_staging

production:
  <<: *default
  database: coursadomicile_production
